//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EStar.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ID { get; set; }
        public int DepartmentID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public int QuestionID { get; set; }
        public int AnswerID { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Category Category { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Question Question { get; set; }
    }
}
